import type { Metadata } from 'next'
import './globals.css'
import Sidebar from '@/components/sidebar'
import NotificationProvider from '@/components/NotificationProvider'

export const metadata: Metadata = {
  title: 'Toko Kita',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen">
        <NotificationProvider>
          <Sidebar />
          <main className="flex-1 overflow-y-auto p-6">{children}</main>
        </NotificationProvider>
      </body>
    </html>
  )
}
